import { NextResponse } from "next/server";
import { GoogleGenAI, Type, Schema } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

const responseSchema: Schema = {
  type: Type.ARRAY,
  items: {
    type: Type.OBJECT,
    properties: {
      etapa: {
        type: Type.STRING,
        description: "Nome da etapa na obra",
      },
      sugestao_busca: {
        type: Type.STRING,
        description: "Termo técnico exato para buscar no SINAPI",
      },
      justificativa: {
        type: Type.STRING,
        description: "Breve texto educativo de por que essa etapa é necessária",
      },
      isAutoGenerated: {
        type: Type.BOOLEAN,
        description: "Sempre true se o prompt_adicional estiver vazio, caso contrário false.",
      }
    },
    required: ["etapa", "sugestao_busca", "justificativa", "isAutoGenerated"],
  },
};

export async function POST(request: Request) {
  try {
    const { nomeObra, descricaoObra, prompt } = await request.json();

    if (!nomeObra && !prompt) {
      return NextResponse.json(
        { error: "Dados do projeto ou prompt são obrigatórios" },
        { status: 400 }
      );
    }

    const systemInstruction = `Você é um Engenheiro de Custos Sênior. Sua tarefa é analisar o NOME e a DESCRIÇÃO de uma obra e gerar um escopo técnico estruturado. 
Para cada serviço, você deve sugerir:
1. O nome da Etapa técnica (ex: Infraestrutura).
2. O termo exato para busca no SINAPI (ex: 'Lastro de concreto magro').
3. A justificativa técnica baseada nas normas brasileiras.
Se o usuário fornecer um prompt adicional, use-o prioritariamente para refinar o escopo inicial adicionando, removendo ou focando em itens específicos. 
Você deve retornar ESTRITAMENTE um array JSON seguindo o schema fornecido.`;

    const contextoInput = `
Nome da Obra: ${nomeObra || "Não informado"}
Descrição do Projeto: ${descricaoObra || "Não informada"}
${prompt ? `\n\nPrompt adicional do usuário (REFINAMENTO / AJUSTE): "${prompt}"` : ""}
    `.trim();

    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash",
      contents: contextoInput,
      config: {
        systemInstruction,
        responseMimeType: "application/json",
        responseSchema,
        temperature: 0.2, // Baixa temperatura para manter a coerência técnica
      },
    });

    const text = response.text;
    if (!text) {
      throw new Error("Nenhum texto retornado pela IA.");
    }

    const parsedJson = JSON.parse(text);

    return NextResponse.json({ data: parsedJson });
  } catch (error: unknown) {
    console.error("Erro na rota /api/suggest-services:", error);
    return NextResponse.json(
      { error: "Erro interno: " + (error instanceof Error ? error.message : String(error)) },
      { status: 500 }
    );
  }
}
